version: "3.8"
services:
  backend:
    build: .
    container_name: student-backend
    ports:
      - "8081:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://piano-mysql:3306/student_ecommerce?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vantoan@123
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      VAADIN_LAUNCH_BROWSER: "false"
      VAADIN_PRODUCTIONMODE: "true"
    restart: always
    networks:
      - piano-network

networks:
  piano-network:
    external: true
